### ISSUE TITLE
No rice option

### ISSUE THREAD

**Issue by ervinjay13** [nzgamer41/virtualubereats#3]
Hello, I am a poor rice farmer from the Philippine countryside. There is no rice option available. This is bad as my family and I cannot eat anything without rice. I would like to feed my starving children. Our rice has to go to our local barangay chief, and I do not have enough for my family. Please add rice option. Thank you.

**Comment by DominicMaas** [comment]
+1

**Comment by nzgamer41** [comment]
Won't fix.

**Comment by DominicMaas** [comment]
I am an entitled user! I demand stuff for free, this is unacceptable. I expect you to take time out of your day to support [feature], or I'll never use [insert product] again!!! 😡

**Comment by ervinjay13** [comment]
Okay, I guess my family and I will die in the rice fields.

Have a good day.
